services:
  web:
    domainname: geyedme.co
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 256M
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
    restart: unless-stopped