services:
  web:
    domainname: geyedme.co
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
    deploy:
      resources:
        limits:
          memory: 512M